### ISSUE TITLE
Removing multiple "object" in panos_address_objects resource gives an error

### ISSUE THREAD

**Issue by rbolneni** [PaloAltoNetworks/terraform-provider-panos#354] opened 2022-09-21 18:29 UTC
## Describe the bug

When removing more than 1 object in panos_address_objects,  I get an error during terraform apply

## Expected behavior

Able to remove multiple object from panos_address_objects in single apply

## Current behavior

When removing more than 1 object in panos_address_objects,  I get an error during terraform apply

## Possible solution

Remove 1 "object" at a time

## Steps to reproduce

1. Create panos_address_objects resource with multiple "object" in it
2. Remove two objects from the resource
3. Apply the change
4. Terraform plan works fine, but apply fails 

## Screenshots
<img width="328" alt="nothandle" src="https://user-images.githubusercontent.com/114103935/191582273-ba7118bb-943e-44f0-93fc-820541aaba53.png">

## Context
Need means to apply delete multiple objects. Deleting 1 object at a a time will be too time consuming when dealing with thousands of object

## Your Environment
    panos = {
      source = "PaloAltoNetworks/panos"
      version = "1.10.3"
    }
Terraform v0.13.7

Panorama 10.1.6

**Comment by shinmog** [comment] 2022-09-21 20:03
I tried 10.1.3, 10.1.6-h6, and 10.2.2.  Of those three, I saw this issue only in 10.1.6-h6, all others worked as expected.

This seems to be a PAN-OS bug introduced somewhere between 10.1.4 and 10.1.6, inclusive.  Please open a TAC case for this.  When working with TAC, please use the new cURL logging options and give TAC those as the reproduction steps, because TAC does not officially support the Terraform provider.

**Comment by shinmog** [comment] 2022-11-21 01:51
This is a duplicate of #350

**Closed by shinmog** 2022-11-21 01:51 UTC
