### ISSUE TITLE
Address Groups and Address Objects deletion errors on apply

### ISSUE THREAD

**Issue by pryorda** [PaloAltoNetworks/terraform-provider-panos#234] opened 2020-03-26 16:26 UTC
Version 1.6.2

When deleting objects that are part of an address group you have to split it into two different runs. One to remove the object from the group and one to delete the object. Do you have any recommendations?

Example Output: 
```
Command => terraform apply -input=true -auto-approve=true   /plans/xx/pan-fw-sac-PROD.plan 
panos_address_object.Blazemeter_N_California_5: Destroying... [id=vsys1:Blazemeter_N_California_5]
panos_address_object.Blazemeter_8: Destroying... [id=vsys1:Blazemeter_8]
panos_address_object.Blazemeter_10: Destroying... [id=vsys1:Blazemeter_10]
panos_address_object.Blazemeter_N_California_7: Destroying... [id=vsys1:Blazemeter_N_California_7]
panos_address_object.Blazemeter_N_California_6: Destroying... [id=vsys1:Blazemeter_N_California_6]
panos_address_object.BlazeMeter_5_Virginia_: Destroying... [id=vsys1:BlazeMeter_5_Virginia_]
panos_address_object.Blazemeter_9: Destroying... [id=vsys1:Blazemeter_9]
panos_address_object.Blazemeter_N_California_3: Destroying... [id=vsys1:Blazemeter_N_California_3]
panos_address_object.BlazeMeter_3_Oregon_: Destroying... [id=vsys1:BlazeMeter_3_Oregon_]
panos_address_object.BlazeMeter_4_Oregon_: Destroying... [id=vsys1:BlazeMeter_4_Oregon_]
panos_administrative_tag.Blazemeter: Creating...
panos_address_object.BlazeMeter_2_N_California_: Destroying... [id=vsys1:BlazeMeter_2_N_California_]
panos_address_object.Blazemeter_N_California_8: Destroying... [id=vsys1:Blazemeter_N_California_8]
panos_address_object.Blazemeter_N_California_2: Destroying... [id=vsys1:Blazemeter_N_California_2]
panos_address_object.BlazeMeter_7_Virginia_: Destroying... [id=vsys1:BlazeMeter_7_Virginia_]
panos_address_object.BlazeMeter_6_Oregon_: Destroying... [id=vsys1:BlazeMeter_6_Oregon_]
panos_address_object.Blazemeter_11: Destroying... [id=vsys1:Blazemeter_11]
panos_address_object.BlazeMeter_1_US_East_: Destroying... [id=vsys1:BlazeMeter_1_US_East_]
panos_address_object.Blazemeter_N_California_4: Destroying... [id=vsys1:Blazemeter_N_California_4]
panos_administrative_tag.Blazemeter: Creation complete after 1s [id=vsys1:Blazemeter]
panos_address_object.BlazeMeter_2: Creating...
panos_address_object.BlazeMeter_1: Creating...
panos_address_object.BlazeMeter_7: Creating...
panos_address_object.BlazeMeter_5: Creating...
panos_address_object.BlazeMeter_3: Creating...
panos_address_object.BlazeMeter_6: Creating...
panos_address_object.BlazeMeter_4: Creating...
panos_address_object.BlazeMeter_2: Creation complete after 1s [id=vsys1:BlazeMeter_2]
panos_address_object.BlazeMeter_1: Creation complete after 1s [id=vsys1:BlazeMeter_1]
panos_address_object.BlazeMeter_4: Creation complete after 1s [id=vsys1:BlazeMeter_4]
panos_address_object.BlazeMeter_5: Creation complete after 1s [id=vsys1:BlazeMeter_5]
panos_address_object.BlazeMeter_7: Creation complete after 1s [id=vsys1:BlazeMeter_7]
panos_address_object.BlazeMeter_6: Creation complete after 1s [id=vsys1:BlazeMeter_6]
panos_address_object.BlazeMeter_3: Creation complete after 1s [id=vsys1:BlazeMeter_3]

Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static
Error:  address-group -> Blazemeter_Access -> static

```

Likely related to #164

**Comment by shinmog** [comment] 2020-03-26 16:35
I suspect you are not properly using resource attribute variables...?  You plan should look like this:

```hcl
resource "panos_address_object" "o1" {
  name = "foo"
  # other stuff...
}

resource "panos_address_object" "o2" {
  name "bar"
  # other stuff....
}

resource "panos_address_group" "grp" {
  name = "baz"
  static_addresses = [panos_address_object.o1.name, panos_address_object.o2.name]
}
```

If you do the above, removal should only be one `terraform apply`.

**Comment by rfc1149** [comment] 2020-05-19 06:03
We're running into this same issue, and all of our address groups refer to resources by attributes:

```
resource "panos_panorama_address_group" "testinggroup" {
  name = "testinggroup"

  static_addresses = [
    panos_panorama_address_object.test.name,
    panos_panorama_address_object.test2.name,
    panos_panorama_address_object.test3.name,
  ]
}
```

Here's an example run from terraform enterprise with a simple PR that deletes the "test" `panos_panorama_address_object` and also removes the line from the `panos_panorama_address_group` that references that object:
Plan output:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
  - destroy

Terraform will perform the following actions:

  # panos_panorama_address_group.testinggroup will be updated in-place
  ~ resource "panos_panorama_address_group" "testinggroup" {
        device_group     = "shared"
        id               = "shared:testinggroup"
        name             = "testinggroup"
      ~ static_addresses = [
          - "test",
            "test2",
            "test3",
        ]
        tags             = [
            "Terraform",
        ]
    }

  # panos_panorama_address_object.test will be destroyed
  - resource "panos_panorama_address_object" "test" {
      - device_group = "shared" -> null
      - id           = "shared:test" -> null
      - name         = "test" -> null
      - tags         = [
          - "Terraform",
        ] -> null
      - type         = "ip-netmask" -> null
      - value        = "10.1.1.1" -> null
    }

Plan: 0 to add, 1 to change, 1 to destroy.
```

Apply Output:
```
Terraform v0.12.17
Initializing plugins and modules...
2020/01/24 11:11:22 [DEBUG] Using modified User-Agent: Terraform/0.12.17 TFE/2472f851cd
panos_panorama_address_object.test: Destroying... [id=shared:test]

Error:  shared -> address-group -> testinggroup -> static
```

It basically looks like the plan has the 2 actions that need to occur, but on the apply, it's doing the delete of the object first, and then trying to remove it to from the group, which the PanOS API errors on, because it needs to happen in the opposite order.

Hope this helps, let me know if i can provide other information to help debug!

**Comment by arusso** [comment] 2020-06-12 16:18
The workaround I'm using for this is to switch from static_addresses to using admin tags and dynamic_match for group membership.

Would love to see this fixed though since I personally prefer static address specification.

**Comment by shinmog** [comment] 2020-08-12 15:09
@pryorda @rfc1149 @arusso 

Terraform knows that the relationships between these objects exist, yet is trying to delete the address object before updating the membership criteria of the address group - this is a core Terraform issue.  I am able to reproduce this behavior in 0.12.29.

I'll do a bit of research and see if this is a known issue or if I need to open a github issue against core Terraform.

**Comment by shinmog** [comment] 2020-09-15 23:59
@pryorda @rfc1149 @arusso 

So after some talking with the Terraform HashiCorp people, addressing this requires two things to be true:

1) You need to be running Terraform 0.13 (I've personally verified that 0.13.2 behaves correctly)
2) The resource needs to have specified [lifecycle.create_before_destroy = true](https://www.terraform.io/docs/configuration/resources.html#create_before_destroy) on it

That second one is slightly problematic as due to hashicorp/terraform#25473 you need to have _created_ the resource with the `create_before_destroy`, you can't add it in after you've deployed the config.  So you'll need to have Terraform destroy the address objects and address group(s) first, then update your plan file to add in the `lifecycle.create_before_destroy` config, then redeploy the config.

As an aside, adding `create_before_destroy` to just the address group is good enough, Terraform seems to be having the address objects inherit this property from the address group.

Furthermore, I've opened up hashicorp/terraform#26254 to push the burden of specifying this to the provider maintainers, but for now users will have to specify this.

Closing this issue out as it is not a provider issue anymore, but if HashiCorp fixes the above, I'll add that flag to all of the panos resources so users don't have to specify it anymore.

**Closed by shinmog** 2020-09-15 23:59 UTC
