### ISSUE TITLE
Data resources

### ISSUE THREAD

**Issue by stobias123** [PaloAltoNetworks/terraform-provider-panos#259] opened 2021-02-09 03:01 UTC
### Is your feature request related to a problem?

I don't like to hard code values into my terraform code. I use data modules whenever possible so that my modules are portable and re-usable. 

I'm unable to write clean code due to the lack of support for data sources in this provider.

### Describe the solution you'd like

There should be data sources available to match all resources. 

### Describe alternatives you've considered

Referencing remote state of other (applied) terraform modules. This is complex, and error prone.]

**Comment by shinmog** [comment] 2021-02-16 21:15
I agree with this sentiment, and the provider is moving in this direction.

My last comment in #104 touches on this, and that issue is similarly worded to this issue.  As such I'm closing this out as a duplicate of that one.

If there is a specific resource you want to get the `panos_address_object` treatment (which means it would get a data source), feel free to open a new GitHub issue for it.

**Closed by shinmog** 2021-02-16 21:15 UTC
Labels: enhancement
